import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 text-white`}
      >
        <header className="shadow-sm">
          <nav className="container mx-auto flex items-center gap-4 p-4">
            <Link href="/" className="text-xl font-semibold">
              Home
            </Link>
            <a href="/repos" className="text-xl font-semibold">
              Repos
            </a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
